#!/usr/bin/env python3
"""
Derives the WordPress paste-in version from index.html, so the two can never
drift apart. Run from the repo root after editing index.html:

    python3 tools/build-wp.py

Output: wordpress/author-websites-content.html — the page body only, with
asset paths rewritten to the WordPress uploads directory, and the standalone
preview's sticky bar and footer stripped (the theme supplies both).
"""

import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "index.html")
OUT = os.path.join(ROOT, "wordpress", "author-websites-content.html")

UPLOADS = "/wp-content/uploads/author-websites"

HEADER = """<!--
	AuthorWings — Author Websites page content
	==========================================================================
	Generated by tools/build-wp.py from index.html. Edit index.html, not this
	file, then re-run the script.

	To use:
	 1. Upload everything in assets/img/ to /wp-content/uploads/author-websites/
	    (the SVGs are what the page references; assets/img/raster/ holds WebP
	    and PNG copies if you would rather serve those).
	 2. Enqueue assets/css/author-websites.css and assets/js/author-websites.js
	    from the child theme — see wordpress/enqueue.php.
	 3. Create the page at /author-websites/, add a single Custom HTML block,
	    and paste everything below.
	 4. Set the page template to one with no container padding (GeneratePress:
	    "Full Width / Contained"), so the full-bleed bands reach the edges.

	The <head> tags and JSON-LD from index.html are not included here — add the
	meta title, description, and schema through the site's SEO panel instead.
-->

"""


def main():
    with open(SRC, encoding="utf-8") as f:
        html = f.read()

    body = re.search(r"<main id=\"ws-main\">(.*?)</main>", html, re.S)
    if not body:
        raise SystemExit("Could not find <main> in index.html")

    content = body.group(1)

    # Point image sources at the WordPress uploads directory.
    content = content.replace('src="assets/img/', f'src="{UPLOADS}/')

    # Re-indent one level out, since the wrapper below replaces <main>.
    content = re.sub(r"^\t", "", content, flags=re.M)

    wrapper = (
        '<div class="aw-ws">\n'
        f"{content.strip()}\n"
        "</div><!-- /.aw-ws -->\n"
    )

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(HEADER + wrapper)

    print(f"Wrote {os.path.relpath(OUT, ROOT)} ({os.path.getsize(OUT):,} bytes)")


if __name__ == "__main__":
    main()
